remove excessive logging

diff --git a/bin/createStone b/bin/createStone
--- a/bin/createStone
+++ b/bin/createStone
@@ -90,7 +90,7 @@ if [[ "$PLATFORM" == MINGW32_NT* || "$PLATFORM" == MSYS_NT* ]] ; then
   exit 1
 fi
 
-set -ex # exit on error
+set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
   echo "the GS_HOME environment variable needs to be defined"; exit 1
 fi
