fix bug in createStone, part deaux [ci skip]

diff --git a/bin/createStone b/bin/createStone
--- a/bin/createStone
+++ b/bin/createStone
@@ -90,7 +90,7 @@ if [[ "$PLATFORM" == MINGW32_NT* || "$PLATFORM" == MSYS_NT* ]] ; then
   exit 1
 fi
 
-set -e # exit on error
+set -ex # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
   echo "the GS_HOME environment variable needs to be defined"; exit 1
 fi
@@ -127,7 +127,7 @@ while getopts "fghns:t:u:i:l:z:c" OPT ; do
 done
 shift $(($OPTIND - 1))
 
-if [ $# -lt 2 ]; then
+if [ $# -le 2 ]; then
   echo "incorrect number of args $# (2 or 3 expected)"; usage; exit 1
 fi
 stoneName="$1"
