add -h option to startClient

diff --git a/bin/createClient b/bin/createClient
--- a/bin/createClient
+++ b/bin/createClient
@@ -72,13 +72,13 @@ while getopts "fht:F" OPT ; do
     f) forceArg=" -f " ;;
     F) deleteClientDir="true" ;;
     t) clientType="${OPTARG}" ;;
-    *) usage; exit 1;;
+    *) echo "unknown option $OPT"; usage; exit 1;;
   esac
 done
 shift $(($OPTIND - 1))
 
 if [ $# -lt 1 ]; then
-  usage; exit 1
+  echo "missing cient name argument"; usage; exit 1
 fi
 clientName=$1
 shift 1
diff --git a/bin/startClient b/bin/startClient
--- a/bin/startClient
+++ b/bin/startClient
@@ -20,7 +20,7 @@ OPTIONS
 
 EXAMPLES
   $(basename $0) -h
-  $(basename $0) todeDev
+  $(basename $0) tode
   $(basename $0) gemtools_329
   $(basename $0) jade_329
 
@@ -34,8 +34,11 @@ if [ "${GS_HOME}x" = "x" ] ; then
 fi
 source ${GS_HOME}/bin/defGsDevKit.env
 
+source ${GS_HOME}/bin/private/shFunctions
+getOpts_help $@
+
 if [ $# -lt 1 ]; then
-  usage; exit 1
+   echo "missing required client name argument"; usage; exit 1
 fi
 clientName=$1
 shift 1
