add windows support to downloadGemStone and installGci

diff --git a/bin/downloadGemStone b/bin/downloadGemStone
--- a/bin/downloadGemStone
+++ b/bin/downloadGemStone
@@ -69,27 +69,30 @@ PLATFORM="`uname -sm | tr ' ' '-'`"
 # Check we're on a suitable 64-bit machine and set gsvers
 case "$PLATFORM" in
     Darwin-i386)
-    OSVERSION="`sw_vers -productVersion`"
-    MAJOR="`echo $OSVERSION | cut -f1 -d.`"
-    MINOR="`echo $OSVERSION | cut -f2 -d.`"
-    CPU_CAPABLE="`sysctl hw.cpu64bit_capable | cut -f2 -d' '`"
-    #
-    # Check the CPU and Mac OS X profile.
-    if [[ $CPU_CAPABLE -ne 1 || $MAJOR -lt 10 || $MINOR -lt 5 ]] ; then
-        echo "[Error] This script requires Mac OS X 10.5 or later on a 64-bit Intel CPU."
-        exit 1
-    fi
-    gsvers="GemStone64Bit${vers}-i386.Darwin"
-    ;;
+      OSVERSION="`sw_vers -productVersion`"
+      MAJOR="`echo $OSVERSION | cut -f1 -d.`"
+      MINOR="`echo $OSVERSION | cut -f2 -d.`"
+      CPU_CAPABLE="`sysctl hw.cpu64bit_capable | cut -f2 -d' '`"
+      #
+      # Check the CPU and Mac OS X profile.
+      if [[ $CPU_CAPABLE -ne 1 || $MAJOR -lt 10 || $MINOR -lt 5 ]] ; then
+          echo "[Error] This script requires Mac OS X 10.5 or later on a 64-bit Intel CPU."
+          exit 1
+      fi
+      gsvers="GemStone64Bit${vers}-i386.Darwin"
+      ;;
     Linux-x86_64)
-    # Linux looks OK
-    gsvers="GemStone64Bit${vers}-x86_64.Linux"
-    ;;
+      # Linux looks OK
+      gsvers="GemStone64Bit${vers}-x86_64.Linux"
+      ;;
+    MINGW32_NT*)
+      gsvers="GemBuilderC${vers}-x86.Windows_NT"
+      ;;
     *)
-    echo "[Error] This script only works on a 64-bit Linux or Mac OS X machine"
-    echo "The result from \"uname -sm\" is \"`uname -sm`\""
-    exit 1
-    ;;
+      echo "[Error] This script only works on a 64-bit Linux or Mac OS X machine"
+      echo "The result from \"uname -sm\" is \"`uname -sm`\""
+      exit 1
+      ;;
 esac
 
 # set zipfile name from gsvers
@@ -139,142 +142,148 @@ gsdevkitSysSetup=$GS_HOME/bin/.gsdevkitSysSetup # if file exists, system setup a
 if [ -e "$gsdevkitSysSetup" ]; then
   echo "Skip operating system configuration steps, system already setup ($gsdevkitSysSetup exists)"
 else
-  # Do a trivial sudo to test we can and get the password prompt out of the way
-  sudo date
-
-  echo "[Info] Setting up shared memory"
-  # Ref: http://developer.postgresql.org/pgdocs/postgres/kernel-resources.html
-  # Ref: http://www.idevelopment.info/data/Oracle/DBA_tips/Linux/LINUX_8tml
-
   case "$PLATFORM" in
-    Linux-x86_64)
-    # use TotalMem: kB because Ubuntu doesn't have Mem: in Bytes
-    totalMemKB=`awk '/MemTotal:/{print($2);}' /proc/meminfo`
-    totalMem=$(($totalMemKB * 1024))
-    # Figure out the max shared memory segment size currently allowed
-    shmmax=`cat /proc/sys/kernel/shmmax`
-    # Figure out the max shared memory currently allowed
-    shmall=`cat /proc/sys/kernel/shmall`
-    ;;
-    Darwin-i386)
-    totalMem="`sysctl hw.memsize | cut -f2 -d' '`"
-    # Figure out the max shared memory segment size currently allowed
-    shmmax="`sysctl kern.sysv.shmmax | cut -f2 -d' '`"
-    # Figure out the max shared memory currently allowed
-    shmall="`sysctl kern.sysv.shmall | cut -f2 -d' '`"
-    ;;
+    MINGW32_NT*) #do nothing
+      ;;
     *)
-    echo "[Error] Can't determine operating system. Check script."
-    exit 1
-    ;;
-  esac
-  totalMemMB=$(($totalMem / 1048576))
-  shmmaxMB=$(($shmmax / 1048576))
-  shmallMB=$(($shmall / 256))
+      # Do a trivial sudo to test we can and get the password prompt out of the way
+      sudo date
 
-  # Print current values
-  echo "  Total memory available is $totalMemMB MB"
-  echo "  Max shared memory segment size is $shmmaxMB MB"
-  echo "  Max shared memory allowed is $shmallMB MB"
+      echo "[Info] Setting up shared memory"
+      # Ref: http://developer.postgresql.org/pgdocs/postgres/kernel-resources.html
+      # Ref: http://www.idevelopment.info/data/Oracle/DBA_tips/Linux/LINUX_8tml
 
-  # Figure out the max shared memory segment size (shmmax) we want
-  # Use 75% of available memory but not more than 2GB
-  shmmaxNew=$(($totalMem * 3/4))
-  [ $shmmaxNew -gt 2147483648 ] && shmmaxNew=2147483648
-  shmmaxNewMB=$(($shmmaxNew / 1048576))
+      case "$PLATFORM" in
+        Linux-x86_64)
+          # use TotalMem: kB because Ubuntu doesn't have Mem: in Bytes
+          totalMemKB=`awk '/MemTotal:/{print($2);}' /proc/meminfo`
+          totalMem=$(($totalMemKB * 1024))
+          # Figure out the max shared memory segment size currently allowed
+          shmmax=`cat /proc/sys/kernel/shmmax`
+          # Figure out the max shared memory currently allowed
+          shmall=`cat /proc/sys/kernel/shmall`
+          ;;
+        Darwin-i386)
+          totalMem="`sysctl hw.memsize | cut -f2 -d' '`"
+          # Figure out the max shared memory segment size currently allowed
+          shmmax="`sysctl kern.sysv.shmmax | cut -f2 -d' '`"
+          # Figure out the max shared memory currently allowed
+          shmall="`sysctl kern.sysv.shmall | cut -f2 -d' '`"
+          ;;
+        *)
+          echo "[Error] Can't determine operating system. Check script."
+          exit 1
+          ;;
+      esac
+      totalMemMB=$(($totalMem / 1048576))
+      shmmaxMB=$(($shmmax / 1048576))
+      shmallMB=$(($shmall / 256))
 
-  # Figure out the max shared memory allowed (shmall) we want
-  # The MacOSX default is 4MB, way too small
-  # The Linux default is 2097152 or 8GB, so we should never need this
-  # but things will certainly break if it's been reset too small
-  # so ensure it's at least big enough to hold a fullsize shared memory segment
-  shmallNew=$(($shmmaxNew / 4096))
-  [ $shmallNew -lt $shmall ] && shmallNew=$shmall
-  shmallNewMB=$(($shmallNew / 256))
+      # Print current values
+      echo "  Total memory available is $totalMemMB MB"
+      echo "  Max shared memory segment size is $shmmaxMB MB"
+      echo "  Max shared memory allowed is $shmallMB MB"
 
-  # Increase shmmax if appropriate
-  if [ $shmmaxNew -gt $shmmax ]; then
-    echo "[Info] Increasing max shared memory segment size to $shmmaxNewMB MB"
-    [ $PLATFORM = "Darwin-i386" ] \
+      # Figure out the max shared memory segment size (shmmax) we want
+      # Use 75% of available memory but not more than 2GB
+      shmmaxNew=$(($totalMem * 3/4))
+      [ $shmmaxNew -gt 2147483648 ] && shmmaxNew=2147483648
+      shmmaxNewMB=$(($shmmaxNew / 1048576))
+
+      # Figure out the max shared memory allowed (shmall) we want
+      # The MacOSX default is 4MB, way too small
+      # The Linux default is 2097152 or 8GB, so we should never need this
+      # but things will certainly break if it's been reset too small
+      # so ensure it's at least big enough to hold a fullsize shared memory segment
+      shmallNew=$(($shmmaxNew / 4096))
+      [ $shmallNew -lt $shmall ] && shmallNew=$shmall
+      shmallNewMB=$(($shmallNew / 256))
+
+      # Increase shmmax if appropriate
+      if [ $shmmaxNew -gt $shmmax ]; then
+        echo "[Info] Increasing max shared memory segment size to $shmmaxNewMB MB"
+        [ $PLATFORM = "Darwin-i386" ] \
 	    && sudo sysctl -w kern.sysv.shmmax=$shmmaxNew
-    [ $PLATFORM = "Linux-x86_64" ] \
+        [ $PLATFORM = "Linux-x86_64" ] \
 	    && sudo bash -c "echo $shmmaxNew > /proc/sys/kernel/shmmax" \
 	    && sudo /bin/su -c "echo 'kernel.shmmax=$shmmaxNew' >>/etc/sysctl.conf"
-  else
-    echo "[Info] No need to increase max shared memory segment size"
-  fi
+      else
+        echo "[Info] No need to increase max shared memory segment size"
+      fi
 
-  # Increase shmall if appropriate
-  if [ $shmallNew -gt $shmall ]; then
-    echo "[Info] Increasing max shared memory allowed to $shmallNewMB MB"
-    [ $PLATFORM = "Darwin-i386" ] && sudo sysctl -w kern.sysv.shmall=$shmallNew
-    [ $PLATFORM = "Linux-x86_64" ] && sudo bash -c "echo $shmallNew > /proc/sys/kernel/shmall"
-  else
-    echo "[Info] No need to increase max shared memory allowed"
-  fi
+      # Increase shmall if appropriate
+      if [ $shmallNew -gt $shmall ]; then
+        echo "[Info] Increasing max shared memory allowed to $shmallNewMB MB"
+        [ $PLATFORM = "Darwin-i386" ] && sudo sysctl -w kern.sysv.shmall=$shmallNew
+        [ $PLATFORM = "Linux-x86_64" ] && sudo bash -c "echo $shmallNew > /proc/sys/kernel/shmall"
+      else
+        echo "[Info] No need to increase max shared memory allowed"
+      fi
 
-  # At this point, shared memory settings contain the values we want, 
-  # put them in sysctl.conf so they are preserved.
-  if [[ ! -f /etc/sysctl.conf || `grep -sc "kern.*m" /etc/sysctl.conf` -eq 0 ]]; then
-    case "$PLATFORM" in
-        Linux-x86_64)
-        echo "# kernelm* settings added by GsDevKit installation" > /tmp/sysctl.conf.$$
-        echo "kernelmmax=`cat /proc/sys/kernel/shmmax`" >> /tmp/sysctl.conf.$$
-        echo "kernelmall=`cat /proc/sys/kernel/shmall`" >> /tmp/sysctl.conf.$$
-        ;;
-        Darwin-i386)
-        # On Mac OS X Leopard, you must have all five settings in sysctl.conf
-        # before they will take effect.
-        echo "# kern.sysv.shm* settings added by GsDevKit installation" > /tmp/sysctl.conf.$$
-        sysctl kern.sysv.shmmax kern.sysv.shmall kern.sysv.shmmin kern.sysv.shmmni \
-        kern.sysv.mseg  | tr ":" "=" | tr -d " " >> /tmp/sysctl.conf.$$
-        ;;
-        *)
-        echo "[Error] Can't determine operating system. Check script."
-        exit 1
-        ;;
-    esac
-    #
-    echo "[Info] Adding the following section to /etc/sysctl.conf"
-    cat /tmp/sysctl.conf.$$
-    sudo bash -c "cat /tmp/sysctl.conf.$$ >> /etc/sysctl.conf"
-    /bin/rm -f /tmp/sysctl.conf.$$
-  else
-    echo "[Info] The following shared memory settings already exist in /etc/sysctl.conf"
-    echo "To change them, remove the following lines from /etc/sysctl.conf and rerun this script"
-    grep "kern.*m" /etc/sysctl.conf
-  fi
+      # At this point, shared memory settings contain the values we want, 
+      # put them in sysctl.conf so they are preserved.
+      if [[ ! -f /etc/sysctl.conf || `grep -sc "kern.*m" /etc/sysctl.conf` -eq 0 ]]; then
+        case "$PLATFORM" in
+          Linux-x86_64)
+            echo "# kernelm* settings added by GsDevKit installation" > /tmp/sysctl.conf.$$
+            echo "kernelmmax=`cat /proc/sys/kernel/shmmax`" >> /tmp/sysctl.conf.$$
+            echo "kernelmall=`cat /proc/sys/kernel/shmall`" >> /tmp/sysctl.conf.$$
+            ;;
+          Darwin-i386)
+            # On Mac OS X Leopard, you must have all five settings in sysctl.conf
+            # before they will take effect.
+            echo "# kern.sysv.shm* settings added by GsDevKit installation" > /tmp/sysctl.conf.$$
+            sysctl kern.sysv.shmmax kern.sysv.shmall kern.sysv.shmmin kern.sysv.shmmni \
+            kern.sysv.mseg  | tr ":" "=" | tr -d " " >> /tmp/sysctl.conf.$$
+            ;;
+          *)
+            echo "[Error] Can't determine operating system. Check script."
+            exit 1
+            ;;
+        esac
+        #
+        echo "[Info] Adding the following section to /etc/sysctl.conf"
+        cat /tmp/sysctl.conf.$$
+        sudo bash -c "cat /tmp/sysctl.conf.$$ >> /etc/sysctl.conf"
+        /bin/rm -f /tmp/sysctl.conf.$$
+      else
+        echo "[Info] The following shared memory settings already exist in /etc/sysctl.conf"
+        echo "To change them, remove the following lines from /etc/sysctl.conf and rerun this script"
+        grep "kern.*m" /etc/sysctl.conf
+      fi
 
-  # Now setup for NetLDI in case we ever need it.
-  echo "[Info] Setting up GemStone netldi service port"
-  if [ `grep -sc "^gs64ldi" /etc/services` -eq 0 ]; then
-    echo '[Info] Adding "gs64ldi  50377/tcp" to /etc/services'
-    sudo bash -c 'echo "gs64ldi         50377/tcp        # Gemstone netldi"  >> /etc/services'
-  else
-    echo "[Info] GemStone netldi service port is already set in /etc/services"
-    echo "To change it, remove the following line from /etc/services and rerun this script"
-    grep "^gs64ldi" /etc/services
-  fi
+      # Now setup for NetLDI in case we ever need it.
+      echo "[Info] Setting up GemStone netldi service port"
+      if [ `grep -sc "^gs64ldi" /etc/services` -eq 0 ]; then
+        echo '[Info] Adding "gs64ldi  50377/tcp" to /etc/services'
+        sudo bash -c 'echo "gs64ldi         50377/tcp        # Gemstone netldi"  >> /etc/services'
+      else
+        echo "[Info] GemStone netldi service port is already set in /etc/services"
+        echo "To change it, remove the following line from /etc/services and rerun this script"
+        grep "^gs64ldi" /etc/services
+      fi
 
-  # Create some directories that GemStone expects; make them writable
-  echo "[Info] Creating /opt/gemstone directory"
-  if [ ! -e /opt/gemstone ]
-    then
-    sudo mkdir -p /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
-    sudo chown $USER:${GROUPS[0]} /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
-    sudo chmod 770 /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
-  else
-    echo "[Warning] /opt/gemstone directory already exists"
-    echo "to replace it, remove or rename it and rerun this script"
-  fi
+      # Create some directories that GemStone expects; make them writable
+      echo "[Info] Creating /opt/gemstone directory"
+      if [ ! -e /opt/gemstone ]
+        then
+        sudo mkdir -p /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
+        sudo chown $USER:${GROUPS[0]} /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
+        sudo chmod 770 /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
+      else
+        echo "[Warning] /opt/gemstone directory already exists"
+        echo "to replace it, remove or rename it and rerun this script"
+      fi
+      ;;
+  esac
   cat - > $gsdevkitSysSetup << EOF
 the presence of this file means that $GS_HOME/bin/downloadGemStone has 
 configured the OS for running GemStone
 EOF
 fi # no sudo usage after this point
 
-if [ -d "$GS_HOME/gemstone/products/$gsvers" ] ; then
-    echo "[Warning] $GS_HOME/gemstone/products/$gsvers already exists"
+if [ -d "$GS_SHARED_DOWNLOADS/products/$gsvers" ] ; then
+    echo "[Warning] $GS_SHARED_DOWNLOADS//products/$gsvers already exists"
     echo "to replace it, remove or rename it and rerun this script"
     echo "...finished $(basename $0)"
     exit 0
@@ -294,49 +303,56 @@ fi
 
 # Download GemStone
 pushd $GS_SHARED_DOWNLOADS/zip >& /dev/null
-if [ ! -e $gss_file ]; then
+  if [ ! -e $gss_file ]; then
     echo "[Info] Downloading $gss_file using ${cmd}"
     $cmd ${ftp_address}/pub/GemStone64/$bucket/$gss_file
-else
+  else
     echo "[Info] $gss_file already exists"
     echo "to replace it, remove or rename it and rerun this script"
-fi
+  fi
 
-# Unzip the downloaded archive into $GS_HOME/gemstone/products/
-echo "[Info] Uncompressing GemStone archive into $GS_HOME/gemstone/products/"
-gs_product=$GS_SHARED_DOWNLOADS/products/$gsvers
-if [ ! -e $gs_product ]
+  # Unzip the downloaded archive into $GS_HOME/gemstone/products/
+  echo "[Info] Uncompressing GemStone archive into $GS_HOME/gemstone/products/"
+  gs_product=$GS_SHARED_DOWNLOADS/products/$gsvers
+  if [ ! -e $gs_product ]
     then
     unzip -q -d $GS_SHARED_DOWNLOADS/products $gss_file
-else
+  else
     echo "[Warning] $GS_SHARED_DOWNLOADS/products/$gsvers already exists"
     echo "to replace it, remove or rename it and rerun this script"
-fi
+  fi
 popd >& /dev/null
 
-# Copy initial system.conf into the Seaside data directory
-echo "[Info] Copying initial system.conf to data directory"
-if [ ! -e $gs_product/seaside/data/system.conf ]
-    then
-    cp $gs_product/seaside/system.conf \
-        $gs_product/seaside/data
-    chmod 644 $gs_product/seaside/data/system.conf
-else
-    echo "[Warning] $gs_product/seaside/data/system.conf already exists"
-    echo "to replace it, remove or rename it and rerun this script"
-fi
 
-# Copy an initial extent to the Seaside data directory
-echo "[Info] Copying initial Seaside repository to data directory"
-if [ ! -e $gs_product/seaside/data/extent0.dbf ]
-    then
-    cp $gs_product/bin/extent0.seaside.dbf \
-        $gs_product/seaside/data/extent0.dbf
-    chmod 644 $gs_product/seaside/data/extent0.dbf
-else
-    echo "[Warning] $gs_product/seaside/data/extent0.dbf already exists"
-    echo "to replace it, remove or rename it and rerun this script"
-fi
+case "$PLATFORM" in
+  MINGW32_NT*) #do nothing
+    ;;
+  *)
+    # Copy initial system.conf into the Seaside data directory
+    echo "[Info] Copying initial system.conf to data directory"
+    if [ ! -e $gs_product/seaside/data/system.conf ]
+      then
+      cp $gs_product/seaside/system.conf \
+         $gs_product/seaside/data
+      chmod 644 $gs_product/seaside/data/system.conf
+    else
+      echo "[Warning] $gs_product/seaside/data/system.conf already exists"
+      echo "to replace it, remove or rename it and rerun this script"
+    fi
+
+    # Copy an initial extent to the Seaside data directory
+    echo "[Info] Copying initial Seaside repository to data directory"
+    if [ ! -e $gs_product/seaside/data/extent0.dbf ]
+      then
+      cp $gs_product/bin/extent0.seaside.dbf \
+         $gs_product/seaside/data/extent0.dbf
+      chmod 644 $gs_product/seaside/data/extent0.dbf
+    else
+      echo "[Warning] $gs_product/seaside/data/extent0.dbf already exists"
+      echo "to replace it, remove or rename it and rerun this script"
+    fi
+    ;;
+esac
 
 #    Copy the gci libraries to client installations
 $GS_HOME/bin/private/installClientGciLibraries $vers
