moving forward with startClient impl

diff --git a/bin/startClient b/bin/startClient
--- a/bin/startClient
+++ b/bin/startClient
@@ -5,85 +5,44 @@
 
 echo "================="
 echo "   GsDevKit script: $(basename $0) $*"
-echo "     Pharo STDOUT routed to: $GS_HOME/pharo/logs/todeClient${postFix}.log"
 echo "================="
 
 usage() {
   cat <<HELP
-USAGE: $(basename $0) [-h] [-f] [-p <postfix>]
+USAGE: $(basename $0) [-h] <client-name> [ <client-specific-args> ]
 
-Launch todeClient image.
+Launch the client named <client-name>.
 
 OPTIONS
   -h 
      display help
-  -f
-     Rebuild the todeClient image
-  -p <postfix>
-     Launch the tode client image created with a matching postfix. If
-     the tode client image does not exist, build it.
 
 EXAMPLES
   $(basename $0) -h
-  $(basename $0) -f
-  $(basename $0)
-  $(basename $0) -p _0  # Launches the image named todeClient_0.image
+  $(basename $0) todeDev
+  $(basename $0) gemtools_329
+  $(basename $0) jade_329
 
 HELP
 }
 
-postFix=""
-force=""
-while getopts "fhp:" OPT ; do
-  case "$OPT" in
-    f) force="true";;
-    h) usage; exit 0 ;;
-    p) postFix="${OPTARG}" ;;
-    *) usage; exit 1 ;;
-  esac
-done
-shift $(($OPTIND - 1))
-
+set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
   echo "the GS_HOME environment variable needs to be defined"
   exit 1
 fi
-
-set -e # exit on error
-pharo=$GS_HOME/pharo
-
-if [ "$force" = "true" ] ; then
- $GS_HOME/bin/createTodeImage -f -p ${postFix}
+source ${GS_HOME}/bin/defGsDevKit.env
+if [ "${GS_GS_CLIENT_DEV}x" = "x" ] ; then
+  echo "the GS_GS_CLIENT_DEV environment variable needs to be defined."
+  exit 1
 fi
 
-if [ ! -e $pharo/todeClient${postFix}.image ] ; then
-  echo "The requested todeClient image: $pharo/todeClient${postFix}.image does not exist"
-  created="false"
-  while [ "$created" = "false" ] ; do
-    read -p "Do you wish to create todeClient${postFix}? [y/n]" yn
-    case $yn in
-      [Yy]* ) $GS_HOME/bin/createTodeImage -p ${postFix}; created="true" ;;
-      [Nn]* ) exit 1;;
-      * ) echo "Please answer yes or no.";;
-    esac
-  done
+if [ $# -lt 1 ]; then
+  usage; exit 1
 fi
+clientName=$1
+shift 1
 
-# Detect operating system
-PLATFORM="`uname -sm | tr ' ' '-'`"
-# Macs with Core i7 use the same software as older Macs
-[ $PLATFORM = "Darwin-x86_64" ] && PLATFORM="Darwin-i386"
+${GS_GS_CLIENT_DEV_CLIENTS}/$clientName/startClient $*
 
-vmArgs=""
-case "$PLATFORM" in
-  Darwin-i386) vmArgs="" ;;
-  Linux-x86_64) vmArgs=" --textenc UTF-8" ;;
-  *)
-    echo "unsupported platform: $PLATFORM"
-    exit 1
-    ;;
-esac
-
-pharo=$GS_HOME/pharo
-unset GEMSTONE_NRS_ALL
-$pharo/pharo-ui $vmArgs $pharo/todeClient${postFix}.image &> $pharo/logs/todeClient${postFix}.log &
+echo "...finished $(basename $0)"
