disallow these commands on windows

diff --git a/bin/startStone b/bin/startStone
--- a/bin/startStone
+++ b/bin/startStone
@@ -37,6 +37,12 @@ EXAMPLES
 HELP
 }
 
+PLATFORM="`uname -sm | tr ' ' '-'`"
+if [[ "$PLATFORM" == MINGW32_NT* ]] ; then
+  echo "This script is a server-only script and cannot be used on Windows"
+  exit 1
+fi
+
 set -e # exit on error
 waitTime=""
 ARG=""
