checkpoint updateClient

diff --git a/bin/updateClient b/bin/updateClient
--- a/bin/updateClient
+++ b/bin/updateClient
@@ -8,6 +8,24 @@ echo "   GsDevKit script: $(basename $0) $*"
 echo "              path: $0"
 echo "================="
 
+usage() {
+  cat <<HELP
+USAGE: $(basename $0) [-h] <client-name>...
+Update GsDevKit client clones and the named clients.
+
+OPTIONS
+  -h 
+     display help
+
+EXAMPLES
+  $(basename $0) -h
+  $(basename $0) tode
+  $(basename $0) gemtools_329
+  $(basename $0) jade_329
+
+HELP
+}
+
 set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
   echo "the GS_HOME environment variable needs to be defined"
@@ -16,11 +34,29 @@ fi
 source ${GS_HOME}/bin/defGsDevKit.env
 
 if [ "${GS_CLIENT_DEV}x" = "x" ] ; then
-  # no cients to update
+  echo "no cients installed"
   exit 0
 fi
 
+source ${GS_HOME}/bin/private/shFunctions
+getOpts_help $@
+
+if [ $# -lt 1 ]; then
+  echo "missing client name args"; usage; exit 1
+fi
+
 $GS_HOME/bin/updateClone client
-$GS_CLIENT_DEV/bin/updateClient
+
+source ${GS_HOME}/bin/private/shFunctions
+getOpts_help $@
+
+for clientName in "$@"
+do
+  if [ -d "${GS_CLIENT_DEV_CLIENTS}/$clientName/" ] ; then
+    ${GS_CLIENT_DEV_CLIENTS}/$clientName/updateClient $clientName
+  else
+    echo "client $clientName does not exist"
+  fi
+done
 
 echo "...finished $(basename $0)"
