Issue #60: final tweak to updateGsDevKit script

diff --git a/bin/updateGsDevKit b/bin/updateGsDevKit
--- a/bin/updateGsDevKit
+++ b/bin/updateGsDevKit
@@ -84,7 +84,7 @@ EXAMPLES
 HELP
 }
 
-set -ex # exit on error
+set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
   echo "the GS_HOME environment variable needs to be defined"
   exit 1
