#112 patch for BUG 46217 for already released GemStone versions (3.2.16 and 3.3.1 have patch as part of release

diff --git a/bin/upgradeStone b/bin/upgradeStone
--- a/bin/upgradeStone
+++ b/bin/upgradeStone
@@ -169,6 +169,93 @@ pushd $upgradeLogDir >& /dev/null
   
 EOF
   
+  # Patch BUG 46217 -- needed for 3.3.0 and pre-3.2.16 GemStone versions.
+  echo "Install patch for Bug 46217"
+  $GEMSTONE/bin/topaz -l -T50000 > $upgradeLogDir/topaz.out << EOF
+  output pushnew $upgradeLogDir/topazPatchBug46217.out only
+  set gemstone $targetStoneName
+  
+  display resultcheck
+  level 0
+
+  display oops
+  iferr 1 stk
+  iferr 2 stack
+  iferr 3 input pop
+  iferr 4 exit 1
+
+! need to patch the the Monticello bootstrap class  MCGemStonePlatform for Bug 46217
+  set user SystemUser pass swordfish
+  login
+  
+  run
+| package symbolDict class theSymbolList gsVersion |
+  gsVersion := System gemVersionAt: 'gsRelease'.
+  (gsVersion matchPattern: #('3.2.' \$*))
+    ifTrue: [
+      (gsVersion matchPattern: #('3.2.1' \$*))
+        ifTrue: [
+          (gsVersion size > 5 and: [ #($7 $8 $9) includes: (gsVersion at: 6) ])
+	    ifTrue: [
+	      "GemStone version 3.2.16 or later - patch not needed"
+	      ^ true ] ] ]
+    ifFalse: [
+      (gsVersion matchPattern: #('3.3.' \$*))
+        ifTrue: [
+          (gsVersion matchPattern: #('3.3.0' \$*))
+            ifFalse: [ 
+	      "GemStone 3.3.1 or later patch not needed"
+	      ^ true ] ]
+	ifFalse: [ 
+	  "no patch available for GemStone versions preceding 3,2.x"
+	  ^true ] ].
+  "patch needed: 3.2.0 thru 3.2.15, and 3.3.0"
+  package := GsPackageLibrary packageNamed: #'Monticello_Globals'.
+  symbolDict := package symbolDict.
+  class := symbolDict at: #'MCGemStonePlatform'.
+  theSymbolList := GsCurrentSession currentSession symbolList.
+  class
+    compileMethod: 'removeClassFromSystem: aClass
+
+  ((GsSession currentSession objectNamed: #UserGlobals) 
+      at: #''GS_BOOTSTRAP_MONTICELLO_SKIP_REMOVE_CLASS'' ifAbsent: [ false ]) 
+    ifTrue: [
+      "Bug 46217 - during bootstrap don''t remove any classes.
+        during initial bootstrap no classes will be removed
+        during upgrade unexpected classes should not be removed during the
+          bootstrap operation" ]
+    ifFalse: [
+	| ar |
+	aClass subclasses isEmpty not ifTrue: [ ^self error: ''class has subclasses'' ].
+	ar := System myUserProfile dictionaryAndSymbolOf: aClass.
+	ar ifNil: [ ^self error: ''class not found in current user profile'' ].
+	(ar at: 1) removeKey: (ar at: 2) ]'
+    dictionaries: theSymbolList
+    category: #'patch bug 46217'
+    intoMethodDict: nil
+    intoCategories: nil
+    intoPragmas: {}
+    environmentId: 0.
+  true
+%
+  commit
+  logout
+
+  set user DataCurator pass swordfish
+  login
+
+  run
+  "Bug 46217 - add for versions pre-dating 3.2.16 and 3.3.0"
+  UserGlobals at: #'GS_BOOTSTRAP_MONTICELLO_SKIP_REMOVE_CLASS' put: true.
+  true
+%
+  commit
+  logout
+
+  output pop
+  exit 0
+EOF
+ 
   # Clear SystemLoginNotification #Subscriptions class variable
   echo "STARTING clear SystemLoginNotification #Subscriptions class variable"
   $GEMSTONE/bin/topaz -l -T50000 > $upgradeLogDir/topaz.out << EOF
@@ -177,7 +264,7 @@ EOF
   
   display resultcheck
   level 0
-  
+
   set user DataCurator pass swordfish
   login
   
@@ -270,6 +357,13 @@ EOF
   iferr 3 input pop
   iferr 4 exit 1
   
+  run 
+  "Bug 46217 - remove for versions pre-dating 3.2.16 and 3.3.0" 
+  UserGlobals removeKey: #'GS_BOOTSTRAP_MONTICELLO_SKIP_REMOVE_CLASS' ifAbsent: []. 
+  true. 
+%
+  commit
+
   run
   UserGlobals associations do: [:assoc |
     assoc value isBehavior
