Issue #31: a bit o cleanup for downloadSmalltalkClient ... windows aware

diff --git a/bin/private/downloadSmalltalkClient b/bin/private/downloadSmalltalkClient
--- a/bin/private/downloadSmalltalkClient
+++ b/bin/private/downloadSmalltalkClient
@@ -96,7 +96,7 @@ case $version in
           ;;
         *) usage; exit 1;;
       esac
-      if [ -e $GS_HOME/shared/pharo/pharo-vm/pharo ] ; then
+      if [ -e "./pharo" ] ; then
         set +e
 missing_32-bit_libs() {
 if [ -e "$GS_HOME/bin/.gsdevkitSetup" ] ; then
@@ -107,12 +107,15 @@ fi
 exit 1
 }
         trap 'missing_32-bit_libs' ERR
-        ./pharo-vm/pharo --help --vm-display-null &> /dev/null 2>&1
+        ./pharo --help --vm-display-null &> /dev/null 2>&1
         trap - ERR
         set -e
       else
-        echo "Pharo download failed --- please try again"
-	exit 1
+        # script needs to run on Windows where we're not concerned about 32 bit libs
+	if [ ! -e "./Pharo.exe" ] ; then
+          echo "Pharo download failed --- please try again"
+	  exit 1
+	fi
       fi
     popd >& /dev/null
     ;;
