try curl if wget is not installed in downloadSmalltalkClient

diff --git a/bin/private/downloadSmalltalkClient b/bin/private/downloadSmalltalkClient
--- a/bin/private/downloadSmalltalkClient
+++ b/bin/private/downloadSmalltalkClient
@@ -61,18 +61,27 @@ case $version in
       echo "Pharo already installed in $directoryPath. To reinstall use \$GS_HOME/private/cleanPharoDirectory and try again."
       exit 0
     fi
+    if [ -e "`which wget`" ]; then
+      cmd="`which wget` -O- "
+    else
+      if [ -e "`which curl`" ] ; then
+        cmd="`which curl` "
+      else
+        echo "Error: wget is not available. Install wget and rerun this script."
+      fi
+    fi
     pushd $directoryPath >& /dev/null
-    case $version in
-      Pharo3.0)
-        wget -O- get.pharo.org/vm30 | bash
-        wget -O- get.pharo.org/30 | bash
-        ;;
-      Pharo4.0)
-        wget -O- get.pharo.org/vm40 | bash
-        wget -O- get.pharo.org/40 | bash
-        ;;
-      *) usage; exit 1;;
-    esac
+      case $version in
+        Pharo3.0)
+          $cmd get.pharo.org/vm30 | bash
+          $cmd -O- get.pharo.org/30 | bash
+          ;;
+        Pharo4.0)
+          $cmd -O- get.pharo.org/vm40 | bash
+          $cmd -O- get.pharo.org/40 | bash
+          ;;
+        *) usage; exit 1;;
+      esac
     popd >& /dev/null
     ;;
   *) usage; exit 1;;
