Issue #62: install* scripts including installOsPrereqs should have a check preventing them from being run as root .... nip any notion of using root early on

diff --git a/bin/utils/installOsPrereqs b/bin/utils/installOsPrereqs
--- a/bin/utils/installOsPrereqs
+++ b/bin/utils/installOsPrereqs
@@ -31,6 +31,13 @@ EXAMPLES
 HELP
 }
 
+# We should run this as a normal user, not root.
+if [ `id | cut -f2 -d= | cut -f1 -d\(` -eq 0 ]
+    then
+    echo "[Error] This script must be run as a normal user, not root."
+    exit 1
+fi
+
 installPrereqsForUbuntu(){
     case "$osVersion" in
       12.04)
